Repository puppetlabs/puppetlabs-helm, pull requests merged in 2019-11, with the labels that each got.

#82 Use subscribe instead of require to gain autoupdating
  manifests/account_config.pp
  spec/classes/account_config_spec.rb
Labels: bugfix

#98 Adding the possibility to add imagePullSecrets
  manifests/account_config.pp
  manifests/init.pp
  manifests/params.pp
  spec/classes/account_config_spec.rb
  spec/classes/init_spec.rb
  templates/tiller-serviceaccount.yaml.epp
Labels: feature

#99 (MODULES-10120) enable simplecov; update to PDK 1.14.1; minor cleanups
  .gitignore
  .pdkignore
  .rubocop.yml
  .sync.yml
  .travis.yml
  Rakefile
  metadata.json
  spec/default_facts.yml
Labels: maintenance
