Repository puppetlabs/puppetlabs-helm, pull requests merged in 2021-02, with the labels that each got.

#140 (IAC-989) - Removal of Inappropriate Terminology
  README.md
  manifests/config.pp
  spec/classes/config_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: bugfix

#141 Update default stable repo and fix acceptance tests
  manifests/params.pp
  spec/acceptance/helm_spec.rb
Labels: bugfix

#143 pdksync - Remove Puppet 5 from testing and bump minimal version to 6.0.0
  .github/workflows/auto_release.yml
  .rubocop.yml
  .sync.yml
  .travis.yml
  metadata.json
Labels: backwards-incompatible

#142 Repair path from acceptance tests
  spec/acceptance/helm_spec.rb
Labels: bugfix

#145 (maint) Update major dependencies prior to release
  metadata.json
Labels: maintenance
